@startuml
class tbl_simba_app_info__appKey信息表 {
  id bigint
  create_time__创建时间 datetime
  modify_time__更新时间 datetime
  create_user__创建者 varchar
  modify_user__更新者 varchar
  project_id__项目id int
  app_key__appKey varchar
  app_secret__appSecret varchar
  deleted int
}
class tbl_simba_online_job_base_publish__实时任务发布表 {
  id__主键 bigint
  online_job_id__任务id bigint
  project_id__所属项目id bigint
  name__任务名称 varchar
  type__任务类型:0-flink int
  manager__责任人，默认为创建者 varchar
  code__代码 longtext
  cpu__任务使用cpu核数默认1 int
  memory__单位G int
  duration__任务持续时长，单位毫秒ms bigint
  worker_ip__任务执行所在的worker机 varchar
  run_status__任务运行状态，1-未启动，2-启动中，3-运行中，4-失败，5-停止 int
  create_time__创建时间 datetime
  create_user__创建者 varchar
  modify_time__修改时间 datetime
  modify_user__修改者 varchar
  deleted__0 int
  application_id__id varchar
  run_time__任务启动时间 datetime
  flink_job_id__flink返回的jobId varchar
  delay_time__业务延迟时间 bigint
  operation_time__操作时间，记录任务运行停止 datetime
  operation_user__任务操作人 varchar
}
class tbl_simba_baseline_instance_v2__基线实例表 {
  id__主键 bigint
  baseline_id__基线业务ID bigint
  alert_id__告警业务ID bigint
  name__基线名称 varchar
  baseline_type__基线类型 tinyint
  default_baseline__1默认 tinyint
  priority__优先级，分为1-9级1最低9最高默认为1 int
  latest_time__小时记录分钟，天记录小时分钟	最晚完成时间 varchar
  alert_time__预警时间 int
  project_id__项目id bigint
  baseline_open__基线是否开启 tinyint
  alert_open__基线绑定的告警是否开启，注意不是告警本身是否开启 tinyint
  instance_status__3异常 tinyint
  instance_type__2破基 tinyint
  trigger_time__触发时间 datetime
  job_ids__存放保障任务 text
}
class tbl_simba_target_statistics_cycle__指标统计周期 {
  id bigint
  statistics_cycle_id__指标统计业务id bigint
  name__统计周期名称 varchar
  abbreviation__缩写 varchar
  remark__描述 varchar
  create_time datetime
  modify_time datetime
  create_user bigint
  modify_user bigint
  deleted int
  tenant_id bigint
}
class log_hive_proxy {
  user_name__用户名 varchar
  action_type varchar
  action_status__执行状态 varchar
  action_msg__执行消息 text
  action_content__执行内容 text
  create_time__创建时间 timestamp
  session_id__sessionId varchar
  proxy_id__代理编号 varchar
  ip__ip varchar
  cost_time__花费时间，单位ms bigint
}
class tbl_simba_tag__标签基础表 {
  id__主键id bigint
  tag_id__标签id bigint
  project_id__项目id bigint
  job_id__任务id bigint
  tenant_id__租户id bigint
  model_id__模块id bigint
  manager_id__责任人id bigint
  tag_name__标签中文名 varchar
  tag__标签英文名 varchar
  entity_id__所属实体id bigint
  life_cycle tinyint
  life_cycle_custom__生命周期天数 int
  description__标签描述 varchar
  create_user__创建用户 bigint
  create_time__创建时间 datetime
  modify_user__修改用户 bigint
  modify_time__修改时间 datetime
  is_lock__标签发布完后才会解锁 tinyint
  locker_id__锁定人id bigint
  lock_time__锁定时间 datetime
  deleted__0:未删除1:已删除 tinyint
  publish__0:未发布1:已发布 tinyint
}
class tbl_simba_dataservice_group_user__api应用组成员 {
  id bigint
  group_id__应用组id bigint
  user_id__用户id bigint
  is_manager__成员角色;1:责任人2:成员 int
  deleted__0 int
}
class tbl_simba_online_job_application_source__实时任务运维数据曲线source列表数据 {
  id int
  projectId__项目id bigint
  online_job_id__任务id bigint
  record_time__记录时间 datetime
  total_count__总数 double
  record_count__数量 double
  type__类别;1:sourceTps2:sourceRps3:sourceDirty4:sourceSubtask5:taskInput6:taskOutput7:sinkRps8:sinkInput int
  record_id__记录id varchar
}
class tbl_simba_job_run_history__运行历史 {
  id bigint
  codeMd5 varchar
  job_id__任务id bigint
  code__代码 longtext
  type__7--flink int
  status__执行失败 int
  runtime__执行时间 datetime
  stats_end_time__任务结束执行时间 datetime
  log_path__日志保存路径 varchar
  result_path__运行结果日志 text
  project_id__项目id bigint
  tenant_id__租户id bigint
  user_id__提交用户id bigint
  worker_ip varchar
  worker_protocol__worker机协议 varchar
  worker_port__worker机端口 varchar
  schedule_resource_id__所属资源组 bigint
}
class tbl_simba_role_permisson__角色权限映射表 {
  id__主键 bigint
  role_id__角色id bigint
  permission_id__权限id bigint
}
class tbl_simba_user_role__用户角色映射表 {
  id__主键 bigint
  project_id__项目id bigint
  user_id__子账号id bigint
  role_id__角色id bigint
}
class demo_tgt {
  id bigint
  age int
  desc varchar
}
class tbl_simba_relation_app_unit__appKey与服务单元关系表 {
  id bigint
  create_time__创建时间 datetime
  modify_time__更新时间 datetime
  create_user varchar
  modify_user varchar
  app_key__appKey varchar
  unit_id__服务单元id bigint
  deleted__是否删除 int
}
class tbl_simba_target_base__基础指标 {
  id bigint
  target_id bigint
  project_id bigint
  data_zone_id bigint
  business_process_id bigint
  english_name__英文名 varchar
  name__中文名 varchar
  data_type__根据hive枚举 int
  remark__描述 varchar
  create_time datetime
  modify_time datetime
  create_user bigint
  modify_user bigint
  deleted int
  tenant_id bigint
}
class tbl_simba_resource_group_model__数据源模块关联表 {
  id bigint
  user_id__租户id bigint
  model_id__模块id bigint
  resource_group_id__数据源id bigint
  create_user__创建人 bigint
  create_time__创建时间 datetime
  modify_user__修改人 bigint
  modify_time datetime
  deleted int
}
class tbl_simba_dataservice_input_output {
  id bigint
  api_id__apiid bigint
  user_id__租户id bigint
  column_name__字段名 varchar
  param_name__参数名 varchar
  column_type__数据类型1:string2:int3:long4:float5:double6:boolean tinyint
  op_type__操作符1:等于2:like3:in tinyint
  required tinyint
  example_value__示例值 varchar
  default_value__默认值 varchar
  description__描述 varchar
  create_time datetime
  create_user bigint
  modify_time datetime
  modify_user bigint
  biz_type__2输出 tinyint
  deleted tinyint
}
class tbl_simba_target_modifier_type__指标修饰词类型 {
  id bigint
  modifier_type_id bigint
  name__名称 varchar
  remark__描述 varchar
  create_time datetime
  modify_time datetime
  create_user bigint
  modify_user bigint
  deleted int
  tenant_id bigint
}
class tbl_simba_job_profile_publish__任务调度属性发布表 {
  id__主键id bigint
  job_id__任务id bigint
  priority__9最高 int
  retry__0 int
  schedule_cycle__cron表达式 varchar
  cycle_type__4：小时\r int
  self_depend__0 int
  custom int
  status__默认0 int
  time_out__超时时间 int
  valid_start_time__调度有效期开始时间 datetime
  valid_end_time__调度有效期结束时间 datetime
}
class simba_log_config {
  code__业务code varchar
  handler_name__处理的beanName varchar
  table_suffix__分表方式 varchar
  table_name__表名 varchar
  create_time timestamp
  create_user varchar
  modify_time timestamp
  modify_user varchar
  deleted int
}
class tbl_simba_dqc_rule_execute_record__规则执行记录表 {
  id bigint
  project_id bigint
  table_id bigint
  job_id bigint
  table_execute_id__表执行记录id bigint
  sql_code varchar
  custom__0否 int
  compare_type__1波动率 int
  upper_limit__上限 decimal
  lower_limit__下限 decimal
  operator__9下降 int
  field_name__字段名 varchar
  rule_status__3异常 int
  template_name__模板名称 varchar
  try_run__1是 int
  business_date__业务时间 date
  execute_time__执行时间 datetime
  table_rule_id__规则执行id bigint
  sample_value__样本值 decimal
  benchmark_value__基准值 decimal
  result_value__结果值 decimal
  remark__异常原因 varchar
  user_id__租户id bigint
  warn_mode varchar
  fixed_value__固定值 decimal
  create_time datetime
  modify_time datetime
  create_user bigint
  modify_user bigint
  deleted int
  partition_flag__0不是 int
  filed_type__2非字符 int
  field_type_str__字段类型 varchar
  timing_time__计划时间 datetime
  cycle_type__4小时 int
  pre_time__上一周期时间 datetime
  next_time__下一周期时间 datetime
  partition_expression__分区表达式 varchar
  except_expression__期望值表达式 varchar
  table_partition varchar
  instance_id__任务实例id bigint
  rule_template_id__模板id bigint
  execute_sql varchar
  resource_group_id__资源组id bigint
}
class tbl_simba_online_job_his_version__任务历史版本表 {
  id__主键 bigint
  online_job_id__任务id bigint
  version__版本号 int
  commit_time__提交时间 datetime
  commit_user__提交者 varchar
  code__代码 longtext
  comment__发布说明 varchar
}
class tbl_simba_config_data_zone__数据域配置表 {
  id bigint
  project_id__项目id bigint
  tenant_id__租户id bigint
  english_name__英文名 varchar
  name__名称 varchar
  abbreviation__缩写 varchar
  remark__描述 varchar
  create_time datetime
  create_user bigint
  modify_time datetime
  modify_user bigint
  deleted int
  plate_id__板块id bigint
  data_zone_id__数据域业务id bigint
  input_code__导入code bigint
}
class mapping {
  bigint bigint
  binary binary
  bit bit
  blob blob
  char char
  date date
  datetime datetime
  decimal decimal
  double double
  enum enum
  float float
  int int
  integer int
  json json
  longblob longblob
  longtext longtext
  mediumblob mediumblob
  mediumint mediumint
  mediumtext mediumtext
  numeric decimal
  real double
  set set
  smallint smallint
  text text
  time time
  timestamp timestamp
  tinyblob tinyblob
  tinyint tinyint
  tinytext tinytext
  varbinary varbinary
  varchar varchar
  year year
}
class tbl_simba_model_table_field {
  id bigint
  modeling_Id__建模表id bigint
  field_name__字段名 varchar
  field_type__字段类型 int
  comment varchar
  type__3派生 tinyint
  create_time datetime
  modify_time datetime
  create_user bigint
  modify_user bigint
  deleted int
  level_id__层级id bigint
  target_id__指标id bigint
  mapping__1是 int
}
class tbl_simba_model_version {
  id bigint
  model_id__模型id bigint
  instance_id__实例id bigint
  job_id__任务id bigint
  version__版本号 varchar
  deploy_flag__0未部署 bigint
  model_size__模型大小 decimal
  log_id__日志id bigint
  create_user bigint
  modify_user bigint
  create_time datetime
  modify_time datetime
  deleted int
  tenant_id bigint
  deploy_path__部署路径 varchar
  delete_path__删除路径字段 varchar
}
class tbl_simba_dqc_rule_open__模板规则配置表 {
  id__主键 bigint
  partition_id__分区表达式主键 bigint
  rule_name__规则名称<表规则、字段规则> varchar
  template_id__模板id bigint
  weak_flag__0—弱，默认1 int
  opt__比较方式，目前支持>>=<<==!=介于 int
  expect_cond__期望条件 varchar
  create_time__创建时间 datetime
  create_user__创建者 varchar
  modify_time__修改时间 datetime
  modify_user__修改者 varchar
  deleted__0 int
}
class store_visitor_log {
  age int
  cameraUniqueCode varchar
  entranceExit int
  entranceExitType int
  faceId varchar
  mapFloor varchar
  merchantId varchar
  rangeNumber varchar
  sex int
  storeId varchar
  userType int
  visitorLogType varchar
  gmtCreate varchar
}
class tbl_simba_dqc_table_rule_config {
  id bigint
  project_id__项目id bigint
  template_name__模板名称 varchar
  template_id__模板id bigint
  table_id__表数据 bigint
  rule_type__3自定义 int
  monitor_enable__0关闭 int
  sql_code__过滤条件，或者自定义sql varchar
  upper_limit__上限 decimal
  lower_limit__下限 decimal
  operator__9下降 int
  field_name__比较的字段名称 varchar
  compare_type__2波动率 int
  user_id__租户id bigint
  create_time datetime
  create_user bigint
  modify_time datetime
  modify_user bigint
  deleted int
  warn_mode__告警模式，跟OPS对应 varchar
  fixed_value__固定值 decimal
  compare_mode__固定值 int
  partition_flag__0不是 int
  field_type_str__字段类型 varchar
}
class tbl_simba_permission__权限表 {
  id__主键 bigint
  parent_id__直接父id bigint
  name__权限名 varchar
  sort__排序 int
  menu_type__可点击权限 int
  permission__权限标识 varchar
  description__描述 varchar
  create_time__创建时间 datetime
  create_user__创建者 varchar
  modify_time__修改时间第一次默认为创建时间 datetime
  modify_user__修改者 varchar
  deleted__0 int
}
class flink_customer_attri_ana__外文书店，用户属性 {
  merchant_id__商户id varchar
  store_code__店铺号 varchar
  dt_date__yyyyMMdd varchar
  dt_sort__10:整栋大楼，20:未来书店 int
  dt_type__2年龄段 int
  total_cnts__总人数 int
  male_cnts__男的人数 int
  female_cnts__女的人数 int
  age_0_17_cnts__0到17岁人数 int
  age_18_25_cnts__18到25岁人数 int
  age_26_35_cnts__26到35岁人数 int
  age_36_45_cnts__36到45岁人数 int
  age_46_55_cnts__46到55岁人数 int
  age_55_cnts__大于55 int
}
class ods_jsn_ipos_vip {
  id__Id int
  pid__pid int
  tn_id__租户ID int
  vpdm__卡号 varchar
  vpmc__会员名称 varchar
  xl_id__系列ID int
  lb_id__VIP类别ID int
  gk_id__顾客ID int
  org_id__发卡组织ID int
  zd_id__发卡终端ID int
  syfw__适用范围0-全部1-按组织机构2-按终端 int
  status__VIP卡状态0-未启用1-正常2-停用4-挂失5-休眠 int
  qy__启用即开卡 int
  qyrq__启用日期 int
  yxrq__到期日期即失效日期默认根据其卡类别的有效期限计算而来当其卡类别中设置了睡眠期限，则要在每次发生消费后更 int
  ty__停止使用 int
  tyrq__停用日期 int
  hklx__换卡类型0升级换卡1挂失换卡2过期换卡9其他 int
  hk__换卡标志 int
  hkrq__换卡日期 int
  gs__挂失标志 int
  gsrq__挂失日期 int
  hx__唤醒 int
  hxrq__唤醒日期 int
  xm__休眠 int
  xmrq__休眠日期 int
  vp_id2__新卡ID int
  scrq__首次消费日期 int
  scsl__首次消费数量 int
  scje__首次消费金额 double
  scdh__首次消费关联小票单号 varchar
  xfcs__累计消费次数 int
  xfsl__累计消费数量 int
  xfje__累计消费金额 double
  yhje__累计优惠金额 double
  xfjf__累计消费积分 int
  dhjf__兑换积分 int
  dqjf__积分余额<当前积分> int
  zjrq__最近消费日 int
  zjsl__最近消费数量 int
  zjje__最近消费金额 double
  zyje__赠予金额 double
  zyjf__赠予积分 int
  password varchar
  cz_dqje__储值卡余额<系统自动回写，不可编辑> double
  cz_yxrq__储值卡余额有效期<系统自动回写，不可编辑> int
  cz_czje__储值卡累计充值金额<系统自动回写，不可编辑> double
  cz_czrq__储值卡最近充值日期<系统自动回写，不可编辑> int
  cz_xfje__储值卡累计消费金额<系统自动回写，不可编辑> double
  cz_xfsl__储值卡累计消费数量<系统自动回写，不可编辑> int
  cz_zcje__储值卡最近充值金额<系统自动回写，不可编辑> double
  cz_xfrq__储值卡最近消费日期<系统自动回写，不可编辑> int
  cz_zxje__储值卡最近消费金额<系统自动回写，不可编辑> double
  cz_zxsl__储值卡最近消费数量<系统自动回写，不可编辑> int
  jdr__建档人 varchar
  jdrq__建档日期 int
  xgr__修改人 varchar
  xgrq__修改日期 int
  bz__备注 varchar
  row_no int
  alterdate int
  lastchanged timestamp
  lbdm__类别代码 varchar
  xldm__系列代码 varchar
  orgdm__终端代码 varchar
  zddm__组织代码 varchar
  gkdm__顾客代码 varchar
  lylx__来源类型0-ipos1-openshop2-taobao3-paipai4-dangdang5- int
  fklx_id__发卡类型id关联ipos_vpfklx表 int
  jfsyfw__0-同折扣适用范围；1-按组织机构；2-按终端 int
  sj__手机 varchar
  sr1__阳历生日 varchar
  cdbh__存档编号 varchar
  sdjf__锁定积分 int
  birth__生日<只保存月份和日期> varchar
  tktx__预处理标记0-没有预处理，1-预停用，2-预升级，3-预休眠 int
  jsdy__经手店员 int
  sszd_id__所属终端ID int
  pp_id__开卡品牌 int
  ssorg_id__所属组织ID int
  sr2__特殊日期 int
  zk__充值折扣 double
  icrm_is_fetch__1：未抓取2:已抓取 int
  zdr__制单人 int
  degrade_checkrq__降级检测时间 int
  ztbz__状态备注 varchar
  czfw__充值范围0-全部1-同投放终端2-同折扣适用范围3-按组织机构4-按终端5-同积分适用范围 int
  ysj__原手机号 varchar
  crm_id__crm的会员id varchar
  firstname__FirstName varchar
  lastname__LastName varchar
  othername__OtherName varchar
  fullname__FullName varchar
  bxje__变现金额 double
  passport_mix_mobile__会员通混淆手机号加密结果为MD5<MD5<"tmall"+$content+$key>> varchar
  passport_is_bind__是否绑定passport0：否，1:是 int
  bsflag varchar
  lyflag varchar
  crm_flag1__CRM数据变更的标记，0-新增，1-变动后待同步，2-同步完成 int
  crm_err_count__CRM同步失败的次数 int
}
class tbl_simba_dataservice_access_output_param__接口入参表 {
  id bigint
  access_id__接口id bigint
  param_name__参数名称 varchar
  column_name__绑定字段 varchar
  param_type__数据类型1:string2:int3:long4:float5:double6:boolean int
  default_value__默认值 varchar
  description__描述 varchar
}
class ads_aid_all__测试数据4志钢 {
  city__所在城市 varchar
  marriage__婚姻状况 varchar
  phone__手机设备 varchar
  reit_city__常用收货城市 varchar
  reg_time__注册时间 varchar
  reg_ip__注册IP varchar
  reg_years__注册年限 varchar
  last_login_time__最后登录时间 varchar
  last_login_ip__最后登录IP varchar
  card_baln__礼卡余额 double
  account_point__账户积分 double
  unit_price_std__历史平均笔单价 double
  buy_account_std__历史消费总金额 double
  buy_count_std__历史消费总次数 int
  card_pay_account__礼品卡支付总金额 double
  card_pay_account_pti__礼品卡支付金额占比 double
  baln_pay_account__账户余额支付总金额 double
  baln_pay_account_pti__账户余额支付金额占比 double
  point_pay_account__积分支付总金额 double
  point_pay_account_pti__积分支付金额占比 double
  other_pay_account__第三方支付总金额 double
  other_pay_account_pti__第三方支付金额占比 double
  most_buy_cate_2nd__最常消费二级类目（次数） int
  most_buy_price_level__最常消费的价格带 varchar
  most_buy_store_name__购买次数最多店铺 varchar
  bug_account_store_name__购买金额最多店铺名字 varchar
  repur_period__复购周期 double
  last_login_time_rgn__最近一次登录距今天数 double
  last_cik_time_rgn__最近一次访问距今天数 double
}
class tbl_simba_resource_workdir__资源目录表 {
  id__主键id bigint
  name__目录名称 varchar
  parent_id__父目录 bigint
  project_id__所属项目 bigint
  description__描述 varchar
  create_time__创建时间 datetime
  create_user__创建者 varchar
  modify_time__修改时间 datetime
  modify_user__修改者 varchar
  deleted__0 int
}
class tbl_simba_server__资源服务器表 {
  id bigint
  server_name__服务器地址 varchar
  resource_group_id__资源组id bigint
  server_address__服务器地址 varchar
  server_used__服务器使用中并发 int
  server_concurrent__服务器并发 int
  description__服务器描述 varchar
  data_application__是否启用数据应用服务；0:否，1:是 tinyint
  data_development__是否启用数据开发服务；0:否，1:是 tinyint
  application_port_address__数据应用服务端口地址 varchar
  development_port_address__数据开大服务端口地址 varchar
  prohibit__是否启用;0:启用1:禁用 tinyint
  server_cpu__服务器cpu int
  server_memory__服务器内存 decimal
  status__服务状态;1:初始化2:正常3:停止 bigint
  deleted__是否删除;0:否，1:是 tinyint
  create_time__创建时间 datetime
  modify_time__修改时间 datetime
  create_user__创建人 bigint
  modify_user__修改人 bigint
  default_value tinyint
  protocol__协议 varchar
}
class tbl_simba_compute_engine__计算引擎表 {
  id bigint
  compute_engine_name__计算引擎名称 varchar
  compute_engine_type__计算引擎类型;1:离线2:实时 smallint
  compute_engine_business__计算引擎厂商;1:CDH2:Apache3:HDP4:华为 smallint
  compute_engine_url__quorun；非高可用hiveserver地址，反之 varchar
  yarn_address__yarn地址 varchar
  high_availability_parameter__高可用参数 longtext
  high_availability__是否高可用；0:否，1:是 tinyint
  compute_engine_password__hiveserver密码 varchar
  compute_engine_username__hiveserver用户名 varchar
  user_id__租户Id bigint
  hdfs_ha__hdfs高可用1:高可用，0:否 tinyint
  hdfs_url__hdfs地址 varchar
  namenode1__hdfs节点1地址 varchar
  namenode2__hdfs节点2地址 varchar
  deleted__是否删除；0:未删除，1:已删除 tinyint
  create_time__创建时间 datetime
  modify_time__修改时间 datetime
  create_user__创建人 bigint
  modify_user__修改人 bigint
  default_value__1:默认 tinyint
  resource_file_path__资源文件hdfs路径 varchar
}
class tbl_simba_config_statistics_cycle__统计周期 {
  id bigint
  project_id bigint
  name__统计名称 varchar
  remark__描述 varchar
  create_user bigint
  modify_user bigint
  create_time datetime
  modify_time datetime
  deleted int
  statistics_cycle_id bigint
}
class tbl_simba_dqc_table_execute_record {
  id bigint
  project_id bigint
  table_id bigint
  job_id bigint
  table_partition varchar
  rule_status__3异常 int
  rule_count__规则数 int
  warn_count__告警数 int
  try_run__1是 int
  business_date__业务时间 date
  execute_time__执行时间 datetime
  user_id bigint
  table_capacity__表大小 decimal
  table_row_number__表行数 bigint
  warn_mode varchar
  create_time datetime
  modify_time datetime
  create_user bigint
  modify_user bigint
  deleted int
  partition_flag__0不是 int
  timing_time datetime
  next_time datetime
  pre_time datetime
  instance_id__任务实例id bigint
  partition_count__分区数 int
  exception_count int
  success_count int
}
class tbl_simba_online_job_base__实时任务基础数据表 {
  id__主键 bigint
  online_job_id__任务id bigint
  project_id__所属项目id bigint
  name__任务名称 varchar
  type__任务类型:1-flink int
  manager__责任人，默认为创建者 varchar
  publish__0 tinyint
  code__代码 longtext
  workdir_id__所属工作目录id bigint
  is_lock__任务发布完成后才会解锁 int
  locker__任务锁定者 varchar
  lock_time__锁定时间 datetime
  description__描述 varchar
  create_time__创建时间 datetime
  create_user__创建者 varchar
  modify_time__修改时间 datetime
  modify_user__修改者 varchar
  deleted__0 int
}
class tbl_simba_config_model_level {
  id bigint
  level_id bigint
  project_id bigint
  tenant_id bigint
  english_name__英文名 varchar
  name__名称 varchar
  remark__描述 varchar
  default_value__1默认 tinyint
  create_time datetime
  modify_time datetime
  create_user bigint
  modify_user bigint
  deleted int
  input_code__业务id bigint
}
class tbl_simba_project_user__子账号项目对应表 {
  id__主键 bigint
  project_id__项目id bigint
  user_id__子账号id bigint
  is_manager__默认为0 int
  description__描述 varchar
  create_time__创建时间 datetime
  create_user__创建者 varchar
  modify_time__修改时间第一次默认为创建时间 datetime
  modify_user__修改者 varchar
  deleted__0 int
}
class tbl_simba_publish_manage_package_detail__发布包管理明细表 {
  id bigint
  package_id__发布包id bigint
  manage_center_id__发布版本id bigint
  name__发布包名称 varchar
  category varchar
  type__任务类型 int
  change_type__2删除 int
  submit_user__提交人 bigint
  submit_time__提交时间 datetime
  data__发布数据 longtext
  status__3发布失败 int
  create_time datetime
  modify_time datetime
  create_user bigint
  modify_user bigint
  deleted int
  project_id bigint
  project_code bigint
  job_attribute__任务属性 int
  package_detail_id__发布包明细业务id bigint
}
class tbl_simba_publish_manage_package__发布包管理 {
  id bigint
  project_id__项目id bigint
  project_code__项目code bigint
  name__发布包名称 varchar
  status__3发布失败 int
  success_count__发布成功数 int
  total__总数 int
  publish_user__发布人 bigint
  publish_time__发布时间 datetime
  create_time datetime
  modify_time datetime
  create_user bigint
  modify_user bigint
  deleted int
  package_id__发布包业务id bigint
}
class tbl_simba_dataservice_api_group_v2__api应用组授权表 {
  id bigint
  group_id bigint
  api_id bigint
  auth_time__授权时间 datetime
  valid_time__有效时间 datetime
  valid_nums__有效次数 int
  auth_user__授权人 bigint
  is_valid__是否授权;1:授权0:解除授权/失效 int
}
class s_trd_tb_order {
  id__????ID bigint
  code__???? varchar
  merchant_code__???? varchar
  shop_code__???? varchar
  user_id__??USER_ID varchar
  total_pay__??? bigint
  total_discount__???? bigint
  total_real_pay__?????? bigint
  pay_way__???? varchar
  pay_type__???? varchar
  from_system__?????? varchar
  pay_log_order_code__????? varchar
  from_customer__faceId?? varchar
  ext__????? varchar
  pay_status__???? bigint
  order_status__???? bigint
  status__1???? bigint
  created_by__??? bigint
  created_on__???? bigint
  last_updated_by__????? bigint
  last_updated_on__?????? bigint
}
class tbl_simba_datamap_table_user_collection__用户及表收藏关系表 {
  id__主键 bigint
  user_id__用户id bigint
  collection_time datetime
  table_id__output表主键 bigint
  tenant_id__租户ID bigint
}
class tbl_simba_online_job_table_his__实时计算源表、维表、结果表历史表 {
  id__主键 bigint
  job_table_id__实时计算历史表主键id bigint
  job_version_id__任务历史表id bigint
  table_name__name或表，结果表为表） varchar
  table_type__维表，2:结果表 int
  datasource_id__数据源id bigint
  datasource_type__数据源类型 int
  mapping_table__映射表 varchar
  column_sql__建表字段sql text
  flink_config__配置信息（json字符串，如源表的消费起始点、时间特征、时间基准列等） text
}
class tbl_simba_dev_resource__数据开发资源管理表 {
  id__主键id bigint
  resource_id__业务ID bigint
  biz_code varchar
  name__资源名称 varchar
  project_id__所属项目 bigint
  type__archive int
  put_simba__是 int
  workdir_id__所属工作目录 bigint
  simba_path__simba的文件路径 varchar
  local_path__本地的文件路径 varchar
  description__描述 varchar
  create_time__创建时间 datetime
  create_user__创建者 varchar
  modify_time__修改时间 datetime
  modify_user__修改者 varchar
  deleted__0 int
  category__2:数据科学算法任务资源 smallint
}
class tbl_simba_datamap_category_v2__数据地图类目表 {
  id__主键 bigint
  name__类目名称 varchar
  tenant_id__租户id bigint
  parent_id__父类目id bigint
  level__类目层级 tinyint
  create_time__创建时间 datetime
  modify_time__修改时间 datetime
  create_user__创建人 bigint
  modify_user__修改人 bigint
  deleted__是否删除；0:未删除，1:已删除 tinyint
}
class tbl_simba_dqc_partitions_open__表达式配置表 {
  id bigint
  partition_name__分区表达式 varchar
  create_time__创建时间 datetime
  create_user__创建者 varchar
  modify_time__修改时间 datetime
  modify_user__修改者 varchar
  deleted__0 int
  table_code__表唯一标示 varchar
}
class db_info_dynamic {
  id int
  db_name varchar
  db_port varchar
  db_user varchar
  db_passwd varchar
  db_ip varchar
}
class tbl_simba_online_job_base_alert_record__报警触发表实时 {
  id__主键 bigint
  job_id__ID bigint
  record_id__触发记录业务ID bigint
  sub_type__5failoverRate tinyint
  alert_id__ID bigint
  status__2解除告警 tinyint
  alert_type__3电话tel varchar
  alert_time__报警时间 datetime
  release_time__解除告警时间 datetime
  release_user__解除告警用户 varchar
  msg_temp__报警模版 text
  alert_open__绑定的告警是否开启，注意不是告警本身是否开启 tinyint
  project_id__项目id bigint
  create_time__创建时间 datetime
  deleted__0 int
}
class tbl_simba_datamap_project_detail__数据地图项目统计表 {
  project_id__项目id bigint
  tenant_id__用户id bigint
  storage_size__存储量 bigint
  table_count__表数量 bigint
  create_time datetime
  modify_time datetime
}
class orders_info__订单表 {
  id__订单ID int
  brand_id__品牌id int
  shop_id__门店id int
  shop_level__门店级别 tinyint
  order_type__3退单 tinyint
  order_scene__4周期购 tinyint
  pid__父级ID int
  order_no__订单号唯一 varchar
  out_order_no__第三方订单号 varchar
  nickname__用户昵称 varchar
  openid__下单用户标识 varchar
  unionid__下单用户标识 varchar
  order_status__6已取消 tinyint
  shipping_status__3已收货 tinyint
  pay_status__4支付失败 tinyint
  pay_msg__支付结果 varchar
  refund_type__4仅退钱<卖家> tinyint
  refund_status__8用户取消申请 tinyint
  pay_channel__支付方式:1微信支付 tinyint
  order_channel__3APP tinyint
  goods_num__商品总数<含赠品> int
  original_price__商品原价 decimal
  sell_price__商品售价 decimal
  reduced_price__优惠价格 decimal
  fee_price__运费 decimal
  use_point__使用积分 int
  pay_price__退款价格 decimal
  real_price__实收 decimal
  pickup_code__提货码 varchar
  pickup_code_img__提货码图片地址 varchar
  receive_type__3货到付款 tinyint
  receive_name__收货人 varchar
  receive_mobile__收货人手机号 varchar
  receive_zipcode__收货邮编 varchar
  receive_province_id__收货省ID int
  receive_province__收货省 varchar
  receive_city_id__收货市ID int
  receive_city__收货市ID varchar
  receive_area_id__收货区ID int
  receive_area__收货区 varchar
  receive_street_id__收货街道ID int
  receive_street__收货街道 varchar
  receive_address__收货详细地址 varchar
  sales_shop_level__销售门店级别 tinyint
  sales_shop_id__销售门店ID int
  sales_shop_code__销售门店code varchar
  sales_shop_detail__提货门店详情 json
  buyer_remark__买家留言 varchar
  express_name__快递公司名称 varchar
  express_code__快递公司标识 varchar
  express_num__快递单号 varchar
  is_invoice__1开 tinyint
  open_invoice__1已开 int
  is_activity__1使用 tinyint
  seller_memo__卖家备注 varchar
  modify_remark__订单状态修改备注 varchar
  cancle_reason__取消订单原因 varchar
  cancle_type__2后台取消 tinyint
  activity_info__优惠信息 json
  activity_info_params json
  cancle_time__取消订单时间 datetime
  confirm_time__确认时间<确认支付时间> datetime
  pay_time__付款时间<支付回调时间> datetime
  delivery_time__发货时间 datetime
  receiving_time__收货时间 datetime
  create_time__下单时间 datetime
  organization_id__机构id int
  open_invoice_time datetime
  now_lng__下单时的经度 varchar
  now_lat__下单时的纬度 varchar
  company_name__下单分公司名称 varchar
  channel__渠道 varchar
  channel_data__渠道值 varchar
  invoice_id int
  ecrm_source__配置地区 varchar
  app__小程序标识 varchar
  mobile varchar
}
class tbl_simba_job_profile__任务调度属性表 {
  id__主键id bigint
  job_id__任务id bigint
  priority__9最高 int
  retry__0 int
  schedule_cycle__cron表达式 varchar
  cycle_type__4：小时\r int
  self_depend__0 int
  custom int
  status__默认0 int
  time_out__超时时间 int
  valid_start_time__调度有效期开始时间 datetime
  valid_end_time__调度有效期结束时间 datetime
}
class tbl_simba_tag_entity__实体表 {
  id__主键id bigint
  entity_id__实体id bigint
  en_name__实体英文名 varchar
  cn_name__实体中文名 varchar
  bind_table_type__0:引用来源表，1:新建来源表 int
  table_name__来源表 varchar
  db_name__来源表所属数据库名 varchar
  data_zone_id__数据域id bigint
  entity_key__实体标识符（实体主键） varchar
  source_job_id__输出表任务id bigint
  tag_job_id__标签逻辑表任务id bigint
  workdir_id__生成标签逻辑表所在的目录id bigint
  project_id__项目id bigint
  tenant_id__租户id bigint
  description__标签描述 varchar
  is_lock__1:是 int
  locker__任务锁定者 bigint
  lock_time__锁定时间 datetime
  create_user__创建用户 bigint
  create_time__创建时间 datetime
  modify_user__修改用户 bigint
  modify_time__修改时间 datetime
  deleted__0:未删除1:已删除 tinyint
}
class db_info {
  id int
  db_name__1111111 varchar
  db_port varchar
  db_user varchar
  db_passwd varchar
  db_ip varchar
  double double
  int int
  smallint smallint
  datetime datetime
  float float
  timestamp timestamp
  chars char
  tinyint tinyint
  date date
  decimal decimal
}
class tbl_simba_job_instance_estimate__基线告警表 {
  id__主键 bigint
  job_id__ID bigint
  cycle_type__4：小时 int
  max_stats_end_time__最迟结束时间 varchar
  create_time__创建时间 datetime
}
class tbl_simba_project_export_import {
  id int
  operation_type__操作类型;1:导入2:导出 smallint
  operation_result__操作结果;1:成功0:失败 smallint
  project_id__项目id int
  operation_user__操作人 int
  operation_time__操作时间 datetime
  description__说明 text
  biz_code__业务标识ID bigint
  version__版本号 varchar
}
class tbl_simba_tag_history__标签历史表 {
  id__主键id bigint
  tag_id__标签id bigint
  tenant_id__租户id bigint
  project_id__项目id bigint
  type__0:基础标签1:复合标签 tinyint
  sub_type__0:实体属性为标签值1:自定义属性与标签值映射关系 tinyint
  value_type__0其他 tinyint
  tag_value__标签值 varchar
  tag_config__标签值JSON格式 text
  publish_user__创建用户 bigint
  publish_time__版本创建时间 datetime
  version__版本号 bigint
  description__发布说明 varchar
}
class tbl_simba_assets_overview {
  plate_id__版块编号 bigint
  tenant_id__租户编号 bigint
  project_count__项目数 int
  table_count__表数量 int
  total_storage_size__存储量 bigint
  data_zone_count__数据域总数 int
  dim_table_count__纬度表总数 int
  business_process_count__业务过程编号 int
  category_count__自定义类目数 int
  create_time__创建日期 timestamp
}
class tbl_simba_resource_group__资源组表 {
  id bigint
  resource_group_name__资源组名称 varchar
  description__描述 varchar
  user_id__租户Id bigint
  deleted__是否删除;0:否1:是 tinyint
  create_user__创建人 bigint
  create_time__创建时间 datetime
  modify_user__修改人 bigint
  modify_time__修改时间 datetime
  default_value__1:默认 tinyint
}
class ads_cig_base_specification__基础管理-规格管理 {
  id__主键 int
  type__指标分类 int
  indicator_code__指标代码 varchar
  name__指标名称 varchar
  params__指标参数 varchar
}
class tbl_simba_role__用户角色表 {
  id__主键 bigint
  name__角色名 varchar
  role_type__角色类型，三种类型：pm、dev、ops varchar
  description__描述 varchar
  create_time__创建时间 datetime
  create_user__创建者 varchar
  modify_time__修改时间 datetime
  modify_user__修改者 varchar
  deleted__0 int
}
class tbl_simba_alert_record__报警触发表 {
  id__主键 bigint
  job_id__ID bigint
  baseline_id__基线业务ID bigint
  latest_time__小时记录分钟，天记录小时分钟	最晚完成时间 varchar
  record_id__触发记录业务ID bigint
  record_type__3实时报警 tinyint
  sub_type__5failoverRate tinyint
  alert_id__ID bigint
  status__2解除告警 tinyint
  alert_type__3电话tel varchar
  alert_time__报警时间 datetime
  release_time__解除告警时间 datetime
  release_user__解除告警用户 varchar
  snapshot__报警快照，存放保障任务/变慢任务/失败任务 text
  msg_temp__报警模版 text
  project_id__项目id bigint
  create_time__创建时间 datetime
  deleted__0 int
  baseline_open__基线是否开启 tinyint
  alert_open__基线绑定的告警是否开启，注意不是告警本身是否开启 tinyint
  baseline_type__基线类型 tinyint
}
class tbl_simba_target_relation__关联表 {
  id bigint
  target_id bigint
  statistics_id bigint
  modifier_ids__逗号分割的修饰词id varchar
}
class tbl_simba_dqc_rule_template__规则模板表 {
  id bigint
  rule_type__4非字符字段 int
  name__模板名称 varchar
  operator__9下降 varchar
  partition_flag__限制分区，1:分区表，2:非分区表，3:全部 smallint
  cycle_type__4：小时 varchar
}
class tbl_simba_dev_func__数据开发函数管理表 {
  id__主键 bigint
  func_id__业务ID bigint
  biz_code varchar
  name__函数名称 varchar
  type__自定义函数 int
  project_id__所属项目 bigint
  class_name__类名 varchar
  resource_ids__资源id varchar
  workdir_id__所属工作目录 bigint
  usage__用途 varchar
  command__命令格式 varchar
  description__参数说明 varchar
  create_time__创建时间 datetime
  create_user__创建者 varchar
  modify_time__修改时间 datetime
  modify_user__修改者 varchar
  deleted__0 int
  func_sql__创建flink函数sql语句 text
  category__2:数据科学算法任务资源 smallint
  custom_func_type__AGGREGATE smallint
}
class tbl_simba_model_table__建模表 {
  id bigint
  tenant_id bigint
  project_id bigint
  type__5.应用表 tinyint
  datasouce_type__0.hive tinyint
  datasource_id__数据源id bigint
  name__表名 varchar
  table_chinaese_name__表中文名 varchar
  table_type__1.外部 tinyint
  table_address__表地址 varchar
  storage_format__2.parqurt tinyint
  table_separator__2.\001 tinyint
  category_id__类目id bigint
  life_cycle__6.自定义 tinyint
  remark varchar
  create_time datetime
  modify_time datetime
  create_user bigint
  modify_user bigint
  deleted int
  job_id int
  table_name_config varchar
  business_table_info__0否 tinyint
  life_cycle_custom__生命周期天数 int
  status__3失败 tinyint
  modeling_id__建模id bigint
  modeling_ddl__建模的ddl text
  table_detail_type__2累计快照 bigint
  manager__责任人 bigint
  data_zone_id__数据域id bigint
  business_process_id__业务过程id bigint
  plate_id__板块id bigint
  table_id__hive对应的tableid bigint
  source_table_name__源表名 varchar
  category_ids varchar
  exception_remark__异常描述 text
  resource_group_id__资源组id bigint
  is_batch_sync__0否 int
  operate_type__1ddl int
  input_code__导入code bigint
  op_flag__1:不可操作 int
}
class demo_complaint_data {
  user_id bigint
  content varchar
  complaint_time varchar
}
class tbl_simba_dataservice_group_v2__数据api应用组 {
  id bigint
  group_id__自动生成 bigint
  group_name__应用组名称 varchar
  user_id__租户id bigint
  manager_id__责任人id bigint
  app_id__appid varchar
  secret__secret varchar
  description__描述 varchar
  create_user bigint
  create_time datetime
  modify_user bigint
  modify_time datetime
  deleted__删除标志0:未删除1:已删除 tinyint
}
class tbl_simba_job_operation_log__操作日志 {
  id__主键 bigint
  type__运维类型，1-任务，2-实例 bigint
  job_id__任务id\n bigint
  instance_id__任务实例id bigint
  operation_time__操作时间 datetime
  operation_user__操作人 varchar
  operation__操作 varchar
}
class address_city {
  address_id bigint
  address varchar
  city varchar
}
class tbl_simba_center_manage_package_detail {
  id bigint
  package_id__发布包id bigint
  manage_center_id__发布管理id bigint
  status__3发布失败 int
  type__任务类型 int
}
class tbl_simba_dqc_template__模板表 {
  id__主键 bigint
  template_type__模板类型 int
  template_name__模板名称 varchar
  rule_type__1—字段 int
  check_way__1—固定值 int
  deleted__0 int
  support_notabpartition__模板是否支持非分区表：0-不支持，1-支持 int
}
class tbl_simba_target_datasource_info {
  id bigint
  datasource_info_id bigint
  name__名称 varchar
  remark__描述 varchar
  create_time datetime
  modify_time datetime
  create_user bigint
  modify_user bigint
  deleted int
  tenant_id bigint
  project_id bigint
}
class tbl_simba_baseline_alert_job__基线告警表 {
  id__主键 bigint
  baseline_alert_id__基线业务ID bigint
  job_id__ID bigint
  project_id__项目id bigint
  create_time__创建时间 datetime
  create_user__创建者 varchar
  modify_time__修改时间 datetime
  modify_user__修改者 varchar
  deleted__0 int
}
class res_org_rank {
  name text,
  avg_score double
  avg_score_rank int
}
class tbl_simba_business_process__业务过程表 {
  id bigint
  project_id bigint
  tenant_id bigint
  plate_id bigint
  english_name varchar
  name varchar
  abbreviation varchar
  function_remark varchar
  remark varchar
  create_time datetime
  modify_time datetime
  create_user bigint
  modify_user bigint
  deleted int
  business_process_id__业务过程id bigint
  data_zone_id__数据域id bigint
  input_code__导入code bigint
}
class tbl_simba_project_environment_resource_group__项目环境资源关系表 {
  id bigint
  resource_group_id__资源组Id bigint
  environment_id__项目环境id bigint
  project_id__项目id bigint
  create_time__创建时间 datetime
}
class tbl_simba_table_permission_application_item__表权限申请权限项 {
  id__主键 bigint
  apply_id__申请id bigint
  item_type__select tinyint
  column_info__字段信息，JSON格式 text
}
class tbl_simba_workdir__目录表 {
  id__主键 bigint
  project_id__项目id bigint
  name__名称 varchar
  parent_id__父目录id bigint
  description__描述 varchar
  create_time__创建时间 datetime
  create_user__创建人 bigint
  modify_time__修改时间 datetime
  modify_user__修改人 bigint
  deleted__0 int
  dir_type__3:资源目录 int
  dir_property__3:flink系统函数） int
  hierarchy__层级 int
}
class tbl_simba_job_base_publish_alert__周期任务报警表 {
  id__主键 bigint
  alert_id__告警业务ID bigint
  job_id__ID bigint
  alert_type__7超时告警 smallint
  timeout_length__超时时长 int
  threshold__阈值 int
  ext_threshold__op为7时另外一端阈值 int
  period__时间周期 int
  cycle_time__连续周期 int
  operator__1大于，2大于等于，3等于，4小于等于，5小于，6不等于，7两者之间 tinyint
  val_type__1是平均值 tinyint
  project_id__项目id bigint
  open__是否开启 tinyint
  job_category__任务分类，0:离线任务，2:数据科学算法任务，3:实时计算 smallint
  create_time__创建时间 datetime
  create_user__创建者 varchar
  modify_time__修改时间 datetime
  modify_user__修改者 varchar
  deleted__0 int
}
class tbl_simba_publish_manage__创建发布包列表 {
  id bigint
  manage_center_id__表唯一键 bigint
  project_code__项目配对code bigint
  project_id bigint
  business_id__业务id，任务id、模型id、函数id、资源id等 bigint
  category__代表的模块，离线任务、标签任务 varchar
  name__业务name，任务name、模型name、函数name、资源name等 varchar
  type__类型：任务类型，数据建模 varchar
  data__导出的数据，json格式。如：{"job":{}"scheduling":{}"modeing":{}} longtext
  submit_time__提交时间 datetime
  submit_user__提交人 bigint
  change_type__变更类型：0新增，1更新，2删除 tinyint
  deleted int
  create_time datetime
  create_user bigint
  modify_time datetime
  modify_user bigint
  job_attribute__任务描述 varchar
  status__1已发布 int
}
class tbl_simba_dataservice_access_filter_relation {
  id int
  access_id int
  filter_id int
  create_time timestamp
  create_user varchar
  modify_time timestamp
  modify_user varchar
  deleted int
}
class tbl_simba_dataservice_api {
  id bigint
  project_id bigint
  user_id bigint
  api_type tinyint
  api_name__api名称 varchar
  api_path__api路径 varchar
  protocol tinyint
  result_type__0：json tinyint
  description__描述 varchar
  status__1-草稿，2-发布 tinyint
  sql_code__sql text
  datasource_id__数据源id bigint
  datasource_type__数据源类型 tinyint
  table_name__表名 varchar
  manager_id__负责人 bigint
  paged__1分页 tinyint
  filter_id__过滤函数id bigint
  create_user bigint
  modify_user bigint
  create_time datetime
  modify_time datetime
  deleted tinyint
  api_id__自动生成apiid bigint
  workdir_id__所属文件目录的id bigint
  cached__1走 tinyint
  http_method__请求方式：0:get tinyint
}
class tbl_simba_online_job_application_his__application曲线历史记录 {
  id bigint
  delay__延时 bigint
  failed__错误数量 bigint
  recordTime__记录时间 datetime
  online_job_id__任务Id bigint
  project_id__项目id bigint
}
class tbl_simba_target_derived__派生指标 {
  id bigint
  target_derived_id bigint
  project_id bigint
  target_id__基础指标id bigint
  english_name__派生指标名称 varchar
  name__派生指标中文 varchar
  data_type__参考hive枚举 int
  create_time datetime
  modify_time datetime
  create_user bigint
  modify_user bigint
  deleted int
  modifier_ids__修饰词id，多个id都逗号分隔 varchar
  statistics_cycle_id__统计周期id bigint
  tenant_id bigint
  remark__派生指标描述 varchar
  alias__别名 varchar
}
class tbl_simba_job_instance_status_log__任务执行日志表 {
  id__主键 bigint
  instance_id__任务实例id bigint
  change_time__任务执行日期 datetime
  pre_status__前一状态 tinyint
  cur_status__当前状态 tinyint
  change_desc__触发事件 varchar
  create_time datetime
}
class tbl_simba_dataservice_dev_workdir {
  id bigint
  workdir_id__自动生成id bigint
  project_id__项目id bigint
  workdir_name__文件目录名称 varchar
  parent_id__父id bigint
  description varchar
  create_time datetime
  create_user bigint
  modify_time datetime
  modify_user bigint
  deleted tinyint
  level__层级 int
}
class tbl_simba_dataservice_api_alert_record__api报警触发表周期 {
  id__主键 bigint
  api_id__ID bigint
  group_id__应用组 int
  record_id__触发记录业务ID bigint
  sub_type__11耗时告警 tinyint
  alert_id__ID bigint
  status__2解除告警 tinyint
  alert_type__3电话tel varchar
  alert_time__报警时间 datetime
  release_time__解除告警时间 datetime
  release_user__解除告警用户 varchar
  msg_temp__报警模版 text
  alert_open__绑定的告警是否开启，注意不是告警本身是否开启 tinyint
  project_id__项目id bigint
  create_time__创建时间 datetime
  deleted__0 int
}
class tbl_simba_business_plate {
  id bigint
  plate_id bigint
  plate_name varchar
  time_partition varchar
  partition_type__1.date tinyint
  default_value__默认值 varchar
  business_date_param_name__业务日期参数名 varchar
  business_date_param_value__业务日期参数值 varchar
  system_date_param_name__系统日期参数名 varchar
  system_date_param_value__系统日期参数值 varchar
  remark varchar
  create_time datetime
  modify_time datetime
  create_user bigint
  modify_user bigint
  deleted int
  tenant_id__租户id bigint
}
class tbl_simba_project_environment__项目环境表 {
  id bigint
  environment_name__环境名称 varchar
  project_id__项目id bigint
  scheduling_queue__调度队列 varchar
  environment_type__（废弃字段） smallint
  database_name__数据库名称 varchar
  resource_file_path__资源文件路径 varchar
  result_quantity__返回结果条数 int
  upload_file_size__上传文件大小限制;单位MB int
  description__描述 varchar
  deleted__是否删除；0:未删除，1:已删除 tinyint
  create_time__创建时间 datetime
  modify_time__修改时间 datetime
  create_user__创建人 bigint
  modify_user__修改人 bigint
  compute_engine_id__计算引擎 bigint
}
class organisation {
  p_id varchar
  id varchar
  name varchar
}
class demo_users {
  user_id bigint
  name varchar
  age varchar
  address_id bigint
}
class tbl_simba_system_config {
  id bigint
  category__类目 varchar
  succinct_name__简写 varchar
  name__名称 varchar
  remark varchar
  tenant_id bigint
  create_time datetime
  modify_time datetime
  create_user bigint
  modify_user bigint
  deleted int
  function_code__功能code varchar
}
class tbl_simba_config_scheduler {
  id bigint
  tenant_id bigint
  project_id bigint
  name__名称 varchar
  sign__标识 varchar
  remark__描述 varchar
  create_time datetime
  modify_time datetime
  create_user bigint
  modify_user bigint
  deleted int
  scheduler_id__调度配置业务id bigint
  default_value__0不默认 tinyint
}
class tbl_simba_dataservice_api_workdir {
  id bigint
  workdir_id__自动生成id bigint
  project_id__项目id bigint
  workdir_name__文件目录名称 varchar
  parent_id__父id bigint
  create_time datetime
  create_user bigint
  modify_time datetime
  modify_user bigint
  deleted tinyint
  level__层级 int
  user_id__租户id bigint
}
class tbl_simba_project_environment_datasource__项目环境数据源关系表 {
  id bigint
  datasource_id__数据源Id bigint
  project_id__项目id bigint
  environment_id__环境Id bigint
  create_time__创建时间 datetime
}
class resource_permission_info {
  id int
  code__权限ccode varchar
  name__权限名称 varchar
  parent_code__父权限code varchar
  value__权限值 varchar
  res_url__路径<{"method":"GET""url":"/api/starter/v1/users/{id}"}> varchar
  type__按钮 tinyint
  sort__排序 int
  icon__图标 varchar
  is_delete__是否删除，0否，1删除 tinyint
  gmt_create__创建时间 datetime
  gmt_modified__更新时间 datetime
}
class tbl_simba_dataservice_api_publish_v2__api发布表 {
  id bigint
  api_id bigint
  user_id__租户id bigint
  api_type tinyint
  api_name__api名称 varchar
  api_path__api路径 varchar
  protocol tinyint
  result_type__0:json tinyint
  description__描述 varchar
  sql_code__脚本模式sql text
  datasource_id__数据源id bigint
  datasource_type__数据源类型 tinyint
  table_name__表名 varchar
  manager_id__负责人id bigint
  paged__1分页 tinyint
  publish_time__发布时间 datetime
  publish_user__发布人 bigint
  create_user bigint
  modify_user bigint
  create_time datetime
  modify_time datetime
  deleted__0:未删除，1:删除 tinyint
  http_method__0:get tinyint
  project_id__项目id bigint
  filter_id__过滤函数id bigint
  total_qps__总体QPS限制 int
  project_qps__单应用的QPS限制 int
  status__0:启用，1:禁用;默认0 tinyint
}
class tbl_simba_dataservice_filter {
  id bigint
  workdir_id__目录id bigint
  filter_name__过滤器名称 varchar
  description__描述 varchar
  code__函数体 text
  user_Id__租户 bigint
  create_user bigint
  create_time datetime
  modify_user bigint
  modify_time datetime
  deleted tinyint
  project_id__项目id bigint
  manager_id__负责人 bigint
}
class tbl_simba_job_supply__实例补数据表 {
  id__主键 bigint
  name__补数据名称 varchar
  runtime__执行时间 datetime
  biz_start_time__业务开始时间 date
  biz_end_time__业务结束时间 date
  channel__并行情况 int
  operation_user varchar
  project_id bigint
}
class user_info {
  id int
  name varchar
  sex varchar
  age int
}
class tbl_simba_manage_center_detail {
  id bigint
  center_detail_id__记录id bigint
  manager_center_id bigint
  business_id__业务唯一id，任务id、模型id、函数id、资源id等 bigint
  project_id bigint
  data__导出的数据，json格式。如：{"job":{}}或者{"modeing":{}} longtext
  version__业务内容的版本号 int
  status__2成功 int
  message__失败原因，成功为空 text
  store_id__对应导出/导入文件的存储记录 bigint
  create_user bigint
  create_time datetime
  modify_user bigint
  modify_time datetime
  deleted int
}
class wh_user {
  name varchar
  age bigint
  sex varchar
  id varchar
}
class tbl_simba_data_dev_workdir_template__任务开发目录模版表 {
  id__主键 bigint
  template_type__模版类型 int
  name__目录名称 varchar
  parent_id__父目录id bigint
  level__目录层级 int
}
class tbl_simba_datamap_table_detail_v2__数据地图表统计 {
  id__主键 bigint
  table_id__tbl_simba_job_output_table主键 bigint
  table_name__表名称 varchar
  cn_name__中文名称 varchar
  table_create_time__表创建时间 datetime
  ddl_update_time__ddl更新时间 datetime
  last_update_time__数据更新时间 datetime
  last_query_time__最后查询时间 datetime
  storage_size__存储量 bigint
  life_cycle__生命周期 bigint
  category_id__分类ID bigint
  description__描述 varchar
  tenant_id__租户id bigint
  project_id bigint
  partition_flag__是否分区---0：否，1-是 int
  create_time datetime
  modify_time datetime
  other_info text,
  inputformat__输入类型 varchar
  outputformat__输出类型 varchar
}
class tbl_simba_job_his_version__任务版本历史表 {
  id__主键 bigint
  job_id__任务id bigint
  version__版本号 int
  commit_time__提交时间 datetime
  commit_user__提交者 varchar
  code__代码 longtext
  comment__注释 varchar
}
class tbl_simba_target_modifier__指标修饰词 {
  id bigint
  modifier_id bigint
  project_id bigint
  modifier_type_id__修饰词类型id bigint
  english_name varchar
  name varchar
  remark varchar
  create_time datetime
  modify_time datetime
  create_user bigint
  modify_user bigint
  deleted int
  tenant_id bigint
}
class demo_src__dqc测试 {
  id bigint
  age int
  desc varchar
}
class tbl_simba_dataservice_filter_workdir {
  id bigint
  project_id__项目id bigint
  workdir_name__目录名称 varchar
  parent_id__父级目录 bigint
  create_time datetime
  create_user bigint
  modify_time datetime
  modify_user bigint
  deleted tinyint
  user_id__租户id bigint
  level__前段默认写死一级 int
}
class tbl_simba_project_environment_compute_engine__项目环境计算引擎关系表 {
  id bigint
  compute_engine_id__计算引擎Id bigint
  project_id__项目id bigint
  environment_id__环境id bigint
}
class tbl_simba_configure__simba配置表 {
  id bigint
  code__配置项 varchar
  value__配置值 varchar
  description__描述 varchar
  create_time__创建时间 datetime
  create_user__创建者 varchar
  modify_time__修改时间第一次默认为创建时间 datetime
  modify_user__修改者第一次默认为创建者 varchar
  deleted int
}
class tbl_simba_project__项目表 {
  id__主键 bigint
  user_id__主账号id bigint
  name__项目名称 varchar
  show_name__项目显示名 varchar
  status__0 int
  manager varchar
  if_download__默认1 int
  download_num__默认200 int
  description__描述 varchar
  create_time__创建时间 datetime
  create_user__创建者 varchar
  modify_time__修改时间第一次默认为创建时间 datetime
  modify_user__修改者 varchar
  deleted__0 int
  manager_id__责任人id bigint
  type__0-离线，1-实时2-数据科学3-数据api int
  version__版本号 varchar
  plate_id__所属业务板块id bigint
  english_name__项目英文名 varchar
  mode__1：简单模式，2：标准模式（双环境模式） int
  project_code__项目代码，隐藏式生成，不开放前端输入 varchar
  env_type__2：开发环境 int
}
class tbl_simba_dataservice_api_alert__周期任务报警表 {
  id__主键 bigint
  alert_id__告警业务ID bigint
  api_id__apiID bigint
  alert_type__11耗时告警 tinyint
  request_count__请求次数 int
  threshold__触发阈值 int
  open__是否开启 tinyint
  user_id__租户ID bigint
  create_time__创建时间 datetime
  create_user__创建者 varchar
  modify_time__修改时间 datetime
  modify_user__修改者 varchar
  deleted__0 int
}
class tbl_simba_dqc_subscribe__订阅告警表 {
  id bigint
  table_id__表id bigint
  job_id__任务id bigint
  subscribe_user_id__订阅人id bigint
  create_time datetime
  create_user bigint
  modify_time datetime
  modify_user bigint
  deleted int
}
class role_permission_info {
  id int
  role_name__角色名称 varchar
  permission__权限list，json格式<[{"code":"101""type":1}{"code":"102""type":1}]> text
  note__描述 varchar
  platform_code__平台code，区分不同平台或项目 varchar
  status__角色启用状态：0->禁用；1->启用 tinyint
  gmt_create__创建时间 datetime
  gmt_modified__更新时间 datetime
  sort__排序 int
}
class tbl_simba_func_workdir__函数目录表 {
  id__主键 bigint
  name__目录名称 varchar
  type__自定义函数目录 int
  parent_id__父目录 bigint
  project_id__所属项目 bigint
  description__描述 varchar
  create_time__创建时间 datetime
  create_user__创建者 varchar
  modify_time__修改时间 datetime
  modify_user__修改人 varchar
  deleted__0 int
}
class tbl_simba_job_base_publish_alert_record__报警触发表周期 {
  id__主键 bigint
  job_id__ID bigint
  record_id__触发记录业务ID bigint
  sub_type__7超时 tinyint
  alert_id__ID bigint
  status__2解除告警 tinyint
  alert_type__3电话tel varchar
  alert_time__报警时间 datetime
  release_time__解除告警时间 datetime
  release_user__解除告警用户 varchar
  msg_temp__报警模版 text
  alert_open__绑定的告警是否开启，注意不是告警本身是否开启 tinyint
  project_id__项目id bigint
  create_time__创建时间 datetime
  deleted__0 int
}
class s_store_visitor_log {
  id__id bigint
  merchant_id__F?id varchar
  store_id__?id varchar
  face_id__?8id varchar
  nick_name__5? varchar
  face_picture__?8gG varchar
  score__?8p int
  base_picture__??gG varchar
  age__t? int
  sex__+0-s-7 int
  passenger_id varchar
  user_id varchar
  in_out__1:?0:?? int
  gmt_create varchar
  gmt_modify varchar
  user_type__0-X-^X int
  level__XI? int
  camera_code__D?4? varchar
  trace_id__?ID varchar
  face_feas__?8y? varchar
  local_time__???? varchar
}
class tbl_simba_dataservice_access__接口表 {
  id bigint
  name__接口名称 varchar
  access_code__接口调用码 varchar
  datasource_id__数据源id bigint
  table_name__表名<向导模式不为空> varchar
  sql_code__接口调用sql（脚本模式不为空） text
  status__1-草稿，2-测试成功，3-测试失败，4-线上发布，5-下线 int
  manager__管理员 varchar
  description__描述 varchar
  create_time__创建时间 datetime
  create_user__创建者 varchar
  modify_time__修改时间第一次默认为创建时间 datetime
  modify_user__修改者第一次默认为创建者 varchar
  deleted int
  is_paging__是否分页:0-否，1-是 int
  is_cached__是否走缓存:0-否，1-是 int
  type__1-脚本模式2-向导模式 int
  datasource_type int
  project_id__项目id bigint
  success_data text,
  publish_time datetime
  use_filter_status__1:使用 int
}
class tbl_simba_dataservice_filter_publish {
  filter_id bigint
  filter_name__过滤函数名称 varchar
  description__描述 varchar
  code__函数体 text
  user_Id bigint
  create_time datetime
  modify_user bigint
  create_user bigint
  modify_time datetime
  deleted tinyint
  publish_time__发布时间 datetime
  publish_user__发布人 bigint
}
class tbl_simba_alert__告警表 {
  id__主键 bigint
  alert_id__告警业务ID bigint
  name__名称 varchar
  default_alert__1默认 tinyint
  alert_type__3电话tel varchar
  repeat_time__告警次数 tinyint
  repeat_interval__告警间隔 int
  quiet_time__免打扰时间段格式:HH:mm<00:00-24:00> varchar
  dest_type__3排班 tinyint
  dest_user__告警对象 text
  project_id__项目id bigint
  open__是否开启 tinyint
  create_time__创建时间 datetime
  create_user__创建者 varchar
  modify_time__修改时间 datetime
  modify_user__修改者 varchar
  deleted__0 int
}
class tbl_simba_table_permission_application__表权限申请表 {
  id__主键 bigint
  apply_id__申请id bigint
  table_id__tbl_simba_job_output_table主键 bigint
  apply_user_id__申请人ID bigint
  apply_time__申请时间 datetime
  confirm_time__确认时间 datetime
  confirm_user_id__确认用户 bigint
  tenant_id__租户id bigint
  project_id__项目id bigint
  status__4未通过 tinyint
  expiration__6:1年 tinyint
  reason__申请理由 varchar
  create_user bigint
  modify_user bigint
  create_time datetime
  modify_time datetime
  deleted__0:未删除，1:删除 tinyint
}
class tbl_simba_job_log__任务执行日志表 {
  id__主键 bigint
  runtime__任务执行日期 datetime
  instance_id__任务实例id bigint
  job_id__任务id bigint
  job_name__任务名称 varchar
  log_path__日志保存路径 varchar
  worker_ip varchar
  status int
  worker_protocol__worker机协议 varchar
  worker_port__worker机端口 varchar
}
class tbl_simba_datamap_table_size {
  tenant_id bigint
  project_id bigint
  table_name varchar
  table_size double
}
class tbl_simba_security_group_api__api安全组关联 {
  id bigint
  security_group_id__自动生成 bigint
  api_id__api_id bigint
  tenant_id__租户id bigint
  project_id__所属项目id bigint
}
class tbl_simba_dataservice_access_input_param__接口入参表 {
  id bigint
  access_id__接口id bigint
  param_name__参数名称 varchar
  column_name__绑定字段 varchar
  param_type__数据类型1:string2:int3:long4:float5:double6:boolean int
  ope_type__操作符1:等于2:like3:in4:大于5:大于等于6:小于7:小于等于 int
  is_required__是否必选0：否1：是 int
  example_value__示例值 varchar
  default_value__默认值 varchar
  description__描述 varchar
}
class tbl_simba_dataservice_api_log__api访问记录表 {
  id bigint
  app_id__appid varchar
  api_id__api_id bigint
  start_time__开始时间 datetime
  end_time__结束时间 datetime
  duration__请求时长 bigint
  ip_addr__ip地址 varchar
  error_type__0:成功其它失败 int
  error_msg__失败信息 text
  deleted__0:未删除，1：删除 int
}
class tbl_simba_message_record__消息记录表 {
  id__主键 bigint
  topic_name__主题 varchar
  content__消息内容 text
  status__2失败 tinyint
  retry_times__重试次数 int
  create_time__创建时间 datetime
  create_user__创建者 bigint
  modify_time__修改时间 datetime
  modify_user__修改者 bigint
  deleted__0 int
  biz_id__业务id varchar
  biz_type__6:删除数据源 int
  user_id__租户id bigint
  message_key__消息key varchar
}
class tbl_simba_job_instance__任务实例表 {
  id__主键 bigint
  next_time__下一次定时时间 datetime
  pre_time__上一次定时时间 datetime
  timing_time__计划时间 datetime
  runtime__执行时间 datetime
  biztime__业务日期 date
  job_id__任务id bigint
  job_name__任务名称 varchar
  type__7--flink int
  manager__责任人 varchar
  instance_type__补跑 int
  status__执行失败 int
  init_time__任务初始化时间 datetime
  ready_time datetime
  stats_start_time__任务开始执行时间 datetime
  stats_end_time__任务结束执行时间 datetime
  retry_no__任务已重试次数默认为0 int
  worker_ip__任务执行所在的worker机 varchar
  cycle_type__4：小时 int
  supply_id bigint
  priority__9最高 int
  retry__0 int
  self_depend__0 int
  freeze__默认0 int
  time_out__超时时间 int
  code__代码 longtext
  schedule_resource_id__资源组id bigint
  tenant_id__租户ID bigint
  worker_protocol__work机协议 varchar
  worker_port__worker机端口 varchar
  log_id__执行日志id bigint
  env_params__环境参数 longtext
  job_category__任务分类，0:离线任务，1:实时计算，2:数据科学算法任务 smallint
  run_params__运行参数 text
  application_id__id varchar
  delay_time__业务延迟时间 bigint
  project_id__项目id bigint
}
class biz_emp__员工表 {
  emp_id__员工id varchar
  emp_name__员工名称 varchar
  org_id__组织id varchar
  emp_score__员工得分 double
  emp_posi__员工岗位 varchar
  createtime datetime
  modifytime datetime
}
class tbl_simba_send_task_record {
  id bigint
  worker_ip__agent地址 varchar
  task_id varchar
  create_time timestamp
  resource_group_id bigint
  worker_protocol__协议 varchar
  worker_port__端口 varchar
  dag_key_str varchar
  task_dag_type int
  user_id bigint
}
class tbl_simba_dataservice_monitor {
  id bigint
  api_id bigint
  invoke_count bigint
  user_id bigint
  avg_consume date
  biz_month varchar
}
class tbl_simba_tag_value__标签值表 {
  id__主键id bigint
  tag_id__标签id bigint
  tenant_id__租户id bigint
  project_id__项目id bigint
  type__0:基础标签1:复合标签 tinyint
  sub_type__0:实体属性为标签值1:自定义属性与标签值映射关系 tinyint
  value_type__0其他 tinyint
  tag_value__标签值 varchar
  tag_config__标签值JSON格式 text
  create_user__创建用户 bigint
  create_time__创建时间 datetime
  modify_user__修改用户 bigint
  modify_time__修改时间 datetime
  deleted__0:未删除1:已删除 tinyint
}
class biz_organization {
  p_id mediumtext,
  id mediumtext,
  name mediumtext
}
class tbl_simba_user__用户表 {
  id__主键 bigint
  parent_id__父id，如果是主账号，为空 bigint
  login_name__登录名 varchar
  password__密码，用MD5加密 varchar
  user_name__用户名 varchar
  phone__手机号 varchar
  email__邮箱 varchar
  status__0 int
  type__子账号：777 int
  description__描述 varchar
  create_time__创建时间 datetime
  create_user__创建者 varchar
  modify_time__修改时间第一次默认为创建时间 datetime
  modify_user__修改者 varchar
  deleted__0 int
  app_key varchar
  secret varchar
  theme__配色主题 int
  admin__是否管理员，默认0为非管理员 int
}
class tbl_simba_dataservice_invoke_log {
  id bigint
  api_id bigint
  app_id varchar
  start_time datetime
  end_time datetime
  consume_time bigint
  ip_addr varchar
  param text,
  result text,
  method_name varchar
  error_msg text,
  error_type varchar
  return_amount bigint
}
class tbl_simba_alarm_set__报警设置表 {
  id__主键 bigint
  project_id__项目id bigint
  job_id__任务id bigint
  job_name__任务名称 varchar
  alarm_reason__成功 int
  alarm_type__多个用’’隔开 varchar
  receiver__多个接收人以“，”隔开 varchar
  status__关 int
  description__描述 varchar
  create_time__创建时间 datetime
  create_user__创建者 varchar
  modify_time__修改时间 datetime
  modify_user__修改者 varchar
  deleted__0 int
  timeout_length__超时时长设置单位分钟 int
}
class tbl_simba_job_output_table__任务输出表 {
  id__主键 bigint
  job_id__任务id bigint
  output_table__输出表 varchar
  life_cycle__生命周期，7，30，90，180，-1，-1为永久 int
  table_code__表唯一标识，md5<output_table> varchar
  user_id__租户id bigint
  project_id__项目id bigint
  partition_flag__是否分区，0:不分区，1分区 smallint
  table_id__表id bigint
  monitor_enable__1开启 smallint
  partition_exp__分区表达式 varchar
  partition_count__分区数 int
}
class tbl_simba_model__算法模型 {
  id bigint
  project_id__项目id bigint
  instance_id__实例id bigint
  job_id__任务id bigint
  tenant_id__租户 bigint
  model_name__模型名称 varchar
  algorithm_type__第一级算法下拉 int
  algorithm_type_second_level__第二级算法下拉 int
  custom_code__自定义代码 varchar
  ivoke_api_path__调用api路径 varchar
  deploy__部署人 bigint
  deploy_time__部署时间 datetime
  enabled__0禁用 int
  create_user__创建人 bigint
  modify_user__修改人 bigint
  modify_time__修改时间 datetime
  create_time__修改时间 datetime
  deleted__0未删除 int
}
class tbl_simba_alert_record_user__报警触发用户表 {
  id__主键 bigint
  record_id__报警记录ID bigint
  record_type__3实时报警 tinyint
  alert_id__ID bigint
  record_user__告警用户 varchar
  status__2失败 tinyint
  alert_type__3电话tel varchar
  email_status__邮件是否成功 tinyint
  msg_status__短信是否成功 tinyint
  tel_status__电话是否成功 tinyint
  alert_time__报警时间 datetime
  create_time__创建时间 datetime
  modify_time__修改时间 datetime
  deleted__0 int
}
class tbl_simba_job_input_table__任务输入表 {
  id__主键 bigint
  job_id__任务id bigint
  input_table__输入表 varchar
  table_id__表id bigint
  table_code varchar
  project_id__项目id bigint
  user_id__用户id bigint
}
class tbl_simba_baseline_job_v2__基线告警表 {
  id__主键 bigint
  baseline_id__基线业务ID bigint
  job_id__ID bigint
  project_id__项目id bigint
  create_time__创建时间 datetime
  create_user__创建者 varchar
  modify_time__修改时间 datetime
  modify_user__修改者 varchar
  deleted__0 int
}
class tbl_simba_tag_property__实体属性表 {
  id__主键id bigint
  property_id__属性id bigint
  entity_id__所属实体id bigint
  tenant_id__租户id bigint
  project_id__项目id bigint
  field_name__字段名 varchar
  field_type__字段类型 int
  description__字段描述 varchar
}
class tbl_simba_baseline_v2__基线表 {
  id__主键 bigint
  baseline_id__基线业务ID bigint
  alert_id__告警业务ID bigint
  name__基线名称 varchar
  baseline_type__基线类型 tinyint
  default_baseline__1默认 tinyint
  priority__优先级，分为1-9级1最低9最高默认为1 int
  latest_time__小时记录分钟，天记录小时分钟	最晚完成时间 varchar
  alert_time__预警时间 int
  project_id__项目id bigint
  baseline_open__基线是否开启 tinyint
  alert_open__基线绑定的告警是否开启，注意不是告警本身是否开启 tinyint
  create_time__创建时间 datetime
  create_user__创建者 varchar
  modify_time__修改时间 datetime
  modify_user__修改者 varchar
  deleted__0 int
}
class tbl_simba_online_dev_workdir__实时任务开发目录表 {
  id__主键 bigint
  workdir_id__目录id bigint
  project_id__项目id bigint
  name__名称 varchar
  parent_id__父目录id，根目录父目录id为-1 bigint
  description__描述 varchar
  create_time__创建时间 datetime
  create_user__创建者 varchar
  modify_time__修改时间 datetime
  modify_user__修改者 varchar
  deleted__0 int
}
class tbl_simba_project_resource_group__项目资源组授权表 {
  id bigint
  resource_group_id__资源组名称 bigint
  project_id__描述 bigint
  code__资源组code varchar
  create_time timestamp
  create_user varchar
  modify_time timestamp
  modify_user varchar
  deleted int
}
class tbl_simba_user_stick__用户置顶映射表 {
  id__主键 bigint
  user_id__子账号id bigint
  project_id__项目id bigint
  sticked__默认不置顶 tinyint
  create_time__创建时间 datetime
  create_user__创建者 varchar
  modify_time__修改时间第一次默认为创建时间 datetime
  modify_user__修改者 varchar
  deleted__0 int
}
class emp {
  emp_id int
  emp_name text,
  org_id int
  emp_score double
}
class tbl_simba_job_base_publish__任务基础数据发布表 {
  id__主键id bigint
  job_id__业务id bigint
  biz_code varchar
  project_id__所属项目id bigint
  name__任务名称 varchar
  type__7--flink int
  period_type__1 int
  manager__任务负责人 varchar
  manager_id__责任人id bigint
  code__代码 longtext
  baseline_id__基线id bigint
  schedule_resource_id__资源组id bigint
  env_params__环境参数 longtext
  create_time__创建时间 datetime
  create_user__创建人 varchar
  modify_time__修改时间 datetime
  modify_user__修改人 varchar
  deleted__0 int
  job_category__任务分类，0:离线任务，1:实时计算，2:数据科学算法任务 smallint
  run_params__运行参数 text
}
class tbl_simba_project_task__项目任务详情关联表 {
  id__主键 bigint
  biztime__业务日期 date
  project_id__所属项目id bigint
  total_failed_task_num__今日任务失败数 int
  total_submit_task_num__已提交任务数 int
  total_task_num__总任务数 int
  total_table_num__离线计算-表数量 int
  total_storage__离线计算-项目占用存储单位<kb> bigint
  total_cancel_task_num__实时计算-停止/取消任务数 int
  create_time__创建时间 datetime
  modify_time__修改时间第一次默认为创建时间 datetime
  deleted__0 int
  type__项目类型 int
  total_model_num__已部署模型数 int
}
class tbl_simba_online_job_base_alert__实时任务报警表 {
  id__主键 bigint
  alert_id__告警业务ID bigint
  job_id__ID bigint
  alert_type__5.failoverRate tinyint
  period__时间周期 int
  cycle_time__连续周期 int
  operator__1大于，2大于等于，3等于，4小于等于，5小于，6不等于，7两者之间 tinyint
  val_type__1是平均值 tinyint
  threshold__阈值 int
  ext_threshold__op为7时另外一端阈值 int
  project_id__项目id bigint
  open__是否开启 tinyint
  create_time__创建时间 datetime
  create_user__创建者 varchar
  modify_time__修改时间 datetime
  modify_user__修改者 varchar
  deleted__0 int
}
class demo {
  id bigint
  name varchar
  GMT_CREATE timestamp
  GMT_MODIFIED timestamp
  tmp2 int
  datetimetest datetime
  aaa decimal
}
class tbl_simba_data_dev_workdir__任务开发目录表 {
  id__主键 bigint
  project_id__项目id bigint
  name__名称 varchar
  parent_id__父目录id bigint
  description__描述 varchar
  create_time__创建时间 datetime
  create_user__创建者 varchar
  modify_time__修改时间 datetime
  modify_user__修改者 varchar
  deleted__0 int
  template_dir__是否模版目录1:是，0否 tinyint
  dir_type__目录类型<0:离线任务目录，1:实时任务目录，2:数据科学任务目录，3:系统函数目录，4:自定义函数目录，5:资源目录 int
}
class tbl_simba_table_name_rule {
  id bigint
  tenant_id bigint
  project_id bigint
  model_level_id__模型层级id bigint
  rule__4.调度 varchar
  create_time datetime
  modify_time datetime
  create_user bigint
  modify_user bigint
  deleted int
  level_name__层级名称 varchar
}
class tbl_simba_datasource__数据源表 {
  id__主键 bigint
  user_id__主账号id bigint
  resource_group_id__资源组Id bigint
  name__名称 varchar
  system_type__数据源系统类别;1:simba<系统生成>2:user<人工创建> smallint
  type__数据源类型:0:mySQL1:sqlServer2:orancle3:postgrsql5:simba6:impala7:mongodb8:odps9:redis11:hbase12:ftp10:sybase int
  url_info varchar
  user_name__用户名 varchar
  password__密码 varchar
  description__描述 varchar
  create_time__创建时间 datetime
  create_user__创建者 varchar
  modify_time__修改时间 datetime
  modify_user__修改者 varchar
  deleted__0 int
  status__联通状态，1:联通0:未联通 smallint
  compute_engine_id__系统数据源记录计算引擎ID人工创建为空 bigint
}
class tbl_simba_dqc_partition_template__分区表达式模板表 {
  id__主键 bigint
  template_name__模板名称 varchar
  memo__模板备注 varchar
  deleted__0 int
}
class tbl_simba_dqc_switch__dqc检查开关 {
  id__主键 bigint
  start_date__生效开始时间 date
  end_date__生效结束时间 date
}
class tbl_simba_datamap_table_category__表及类目映射表 {
  id__主键 bigint
  category_ids__类目id varchar
  table_code__表的唯一标识 varchar
}
class tbl_simba_security_group__安全组 {
  id bigint
  security_group_id__自动生成 bigint
  security_group_name__应用组名称 varchar
  tenant_id__租户id bigint
  project_id__所属项目id bigint
  type__2白名单 tinyint
  ip__地址内容 text
  create_user bigint
  create_time datetime
  modify_user bigint
  modify_time datetime
  deleted__删除标志0:未删除1:已删除 tinyint
}
class tbl_simba_alarm_log__报警记录表 {
  id__主键 bigint
  project_id__项目id bigint
  alarm_time__报警发送时间 datetime
  job_id__任务id bigint
  job_name__任务名称 varchar
  alarm_reason__成功 int
  alarm_type__多个用’’隔开 varchar
  receiver__接收人 varchar
}
class tbl_simba_type_conf__simba配置表 {
  id int
  type_group_id__类型分组 int
  type_group_name__组名称 varchar
  type_code__类型关键字 int
  type_value__类型值 varchar
  disable__是否禁用，0-否，1-是 int
}
class tbl_simba_datasource_model__数据源模块关联表 {
  id bigint
  user_id__租户id bigint
  model_id__模块id bigint
  create_user__创建人 bigint
  create_time__创建时间 datetime
  modify_user__修改人 bigint
  modify_time datetime
  datasource_id__数据源id bigint
  deleted int
}
class tbl_simba_online_job_application__实时任务运维数据曲线 {
  id int
  failover_rate__失败率 double
  delay__业务延时 bigint
  intervals__数据时间间隔 bigint
  retetion__数据滞留时间 bigint
  project_id__项目类型Id bigint
  online_job_id__实时任务Id bigint
  record_time__记录时间 datetime
}
class tbl_simba_project_version_cover {
  id bigint
  cover_id bigint
  file_path__文件路径 varchar
  project_id__导入项目的id bigint
  data__导入文本 text
  category varchar
  business_id__业务id bigint
  create_time datetime
  modify_time datetime
  create_user bigint
  modify_user bigint
  deleted int
}
class tbl_simba_dataservice_unit__服务单元表 {
  id bigint
  project_id__项目id bigint
  name__单元名称 varchar
  code__单元调用码 varchar
  manager__如果多个用分隔 varchar
  description__描述 varchar
  create_time__创建时间 datetime
  create_user__创建者 varchar
  modify_time__修改时间第一次默认为创建时间 datetime
  modify_user__修改者第一次默认为创建者 varchar
  deleted int
}
class tbl_simba_baseline_alert__基线表 {
  id__主键 bigint
  baseline_alert_id__基线业务ID bigint
  alert_id__告警业务ID bigint
  name__基线名称 varchar
  baseline_type__基线类型 tinyint
  priority__优先级，分为1-9级1最低9最高默认为1 int
  latest_time__小时记录分钟，天记录小时分钟	最晚完成时间 varchar
  alert_time__预警时间 int
  project_id__项目id bigint
  open__是否开启 tinyint
  create_time__创建时间 datetime
  create_user__创建者 varchar
  modify_time__修改时间 datetime
  modify_user__修改者 varchar
  deleted__0 int
}
class tbl_simba_dqc_check_result_open__规则校验结果表 {
  id__主键 bigint
  runtime__规则校验时间 datetime
  rule_id__规则id bigint
  partition_name__检测的具体分区 varchar
  group_no__规则分组，试跑已try开头，正常跑normal开头，后面加时间戳（毫秒） varchar
  start_time__校验开始时间 datetime
  end_time__校验结束时间 datetime
  status__种状态：0—未运行、3—校验中、4—通过、5-失败、6-异常 int
  opt int
  expect_cond varchar
  sample_result__采样结果 varchar
  worker_address varchar
  log_path varchar
  init_time__初始化时间 datetime
  try_flag__试跑标识：1-试跑；0-正常调用 int
  table_code__表唯一标识 varchar
}
class tbl_simba_field_mapping__数据导入字段映射表 {
  source_field__源字段类型 varchar
  target_field__目标字段类型 varchar
  source_type__源数据源类型 int
  target_type__目标数据源类型 int
}
class tbl_simba_datamap_overview {
  tenantId bigint
  project_amount int
  table_amount int
  total_size double
}
class tbl_simba_publish_manage_store__发布包存储表 {
  id bigint
  store_id__业务唯一键 bigint
  store_type__存储类型，1-oss2-hdfs3-ftp varchar
  store_config__json格式 varchar
  create_user bigint
  create_time datetime
  modify_user bigint
  modify_time datetime
  deleted int
  package_detail_id__发布包明细业务id bigint
}
class tbl_simba_dataservice_unit_access__服务单元与接口对照表 {
  id bigint
  unit_id__服务单元id bigint
  access_id__接口id bigint
}
class tbl_simba_project_datasource__项目数据源授权表表 {
  id bigint
  datasource_id__数据源Id bigint
  project_id__项目id bigint
  code__数据源code varchar
  create_time timestamp
  create_user varchar
  modify_time timestamp
  modify_user varchar
  deleted int
}
class grant_permission {
  id int
  principal_part__主体<用户账号> varchar
  principal_part_type__主体类型，1用户，2运用<默认为1> tinyint
  resources__资源<角色> varchar
  resources_type__资源类型，1角色，2权限<默认1> tinyint
  space_code__空间代码<项目code> varchar
  note__描述 varchar
  status__授权是否开启：0->禁用；1->启用 tinyint
  gmt_create__创建时间 datetime
  gmt_modified__更新时间 datetime
}
class tbl_simba_assets_top {
  plate_id__版块编号 bigint
  type__1:表关联数，2:表占用存储，3:项目占用存储 int
  name__横轴名 varchar
  name_value__纵轴值 bigint
  create_time timestamp
}
class tbl_simba_job_base__任务基础数据表 {
  id__主键 bigint
  job_id__业务id bigint
  biz_code varchar
  project_id__所属项目id bigint
  name__任务名称 varchar
  type__7--flink int
  period_type__任务周期类型:0--手工任务、1--周期任务 int
  manager__责任人，默认为创建者 varchar
  manager_id__责任人id bigint
  publish__0 int
  code__代码 longtext
  datax_code__数据同步代码 longtext
  workdir_id__所属工作目录 bigint
  is_lock__任务发布完成后才会解锁 int
  locker__任务锁定者 varchar
  lock_time__锁定时间 datetime
  baseline_id__所属基线 bigint
  schedule_resource_id__所属资源组 bigint
  env_params__环境参数 longtext
  description__描述 varchar
  create_time__创建时间 datetime
  create_user__创建者 varchar
  modify_time__修改时间 datetime
  modify_user__修改者 varchar
  deleted__0 int
  job_category__任务分类，0:离线任务，1:实时计算，2:数据科学算法任务 smallint
  run_params__运行参数 text
  job_mode__实时任务模式（0:可配置模式，1:脚本模式> int
}
class tbl_simba_baseline_check_his__基线检查历史表 {
  id__主键id bigint
  project_id__所属项目id bigint
  baseline_id__基线id bigint
  status__是否破线破线、正常 varchar
  end_time__预计时间 varchar
  biztime__业务时间 date
}
class tbl_simba_config_field_mapping__表字段映射 {
  id bigint
  project_id bigint
  tenant_id bigint
  datasource_type__1oracle int
  source_field_type__源字段类型 int
  target_field_type__目标字段类型 int
  remark varchar
  create_time datetime
  modify_time datetime
  create_user bigint
  modify_user int
  deleted int
}
class tbl_simba_baseline_alert_record__基线报警触发表 {
  id__主键 bigint
  record_id__触发记录业务ID bigint
  baseline_id__基线业务ID bigint
  baseline_name__基线名称 varchar
  baseline_open__基线是否开启 tinyint
  alert_open__基线绑定的告警是否开启，注意不是告警本身是否开启 tinyint
  baseline_type__基线类型 tinyint
  sub_type tinyint
  latest_time__小时记录分钟，天记录小时分钟	最晚完成时间 varchar
  alert_time__报警时间 datetime
  pre_alert__预警时间 int
  status__2解除告警 tinyint
  release_time__解除告警时间 datetime
  release_user__解除告警用户 varchar
  snapshot__报警快照，存放保障任务/变慢任务/失败任务 text
  alert_id__ID bigint
  alert_type__3电话tel varchar
  msg_temp__报警模版 text
  project_id__项目id bigint
  create_time__创建时间 datetime
  deleted__0 int
}
class tbl_simba_requrest_record__请求记录表 {
  id bigint
  create_time__创建时间 datetime
  modify_time__更新时间 datetime
  request_begin_time__请求起始时间 double
  request_ip__请求ip varchar
  u_code__服务单元code varchar
  a_code__请求地址 varchar
  request_param__请求参数json字符串 varchar
  result_state__结果状态1为成功0为失败 int
  result_data__失败时存储失败原因 varchar
  request_time__存储毫秒级 int
}
class tbl_simba_model_table_field_relation {
  id bigint
  modeling_id__模型表id bigint
  field_id__字段id bigint
  relation_modeling_id__关联表id bigint
  relation_field_id__关联字段id bigint
  create_time datetime
  modify_time datetime
  create_user bigint
  modify_user bigint
  deleted int
  relation_field_name__关联字段名 varchar
}
class tbl_simba_online_job_table {
  id__主键 bigint
  job_table_id__实时计算表主键id bigint
  job_id__任务id bigint
  table_name__name或表，结果表为表） varchar
  table_type__维表，2:结果表 int
  datasource_id__数据源id bigint
  datasource_type__数据源类型 int
  mapping_table__映射表 varchar
  column_sql__建表字段sql text
  flink_config__配置信息（json字符串，如源表的消费起始点、时间特征、时间基准列等） text
  create_time__创建时间 datetime
  create_user__创建者 bigint
  modify_time__修改时间 datetime
  modify_user__修改者 bigint
  deleted__0 int
}
tbl_simba_tag__标签基础表 "N" -- "1" tbl_simba_job_base__任务基础数据表
tbl_simba_job_run_history__运行历史 "N" -- "1" tbl_simba_job_base__任务基础数据表
tbl_simba_role_permisson__角色权限映射表 "N" -- "1" tbl_simba_role__用户角色表
tbl_simba_user_role__用户角色映射表 "N" -- "1" tbl_simba_role__用户角色表
tbl_simba_job_profile_publish__任务调度属性发布表 "N" -- "1" tbl_simba_job_base__任务基础数据表
tbl_simba_dqc_rule_execute_record__规则执行记录表 "N" -- "1" tbl_simba_job_base__任务基础数据表
tbl_simba_model_version "N" -- "1" tbl_simba_job_base__任务基础数据表
tbl_simba_dqc_table_execute_record "N" -- "1" tbl_simba_job_base__任务基础数据表
tbl_simba_online_job_base_alert_record__报警触发表实时 "N" -- "1" tbl_simba_job_base__任务基础数据表
tbl_simba_job_profile__任务调度属性表 "N" -- "1" tbl_simba_job_base__任务基础数据表
tbl_simba_job_instance_estimate__基线告警表 "N" -- "1" tbl_simba_job_base__任务基础数据表
tbl_simba_alert_record__报警触发表 "N" -- "1" tbl_simba_job_base__任务基础数据表
tbl_simba_model_table__建模表 "N" -- "1" tbl_simba_job_base__任务基础数据表
tbl_simba_job_operation_log__操作日志 "N" -- "1" tbl_simba_job_base__任务基础数据表
tbl_simba_baseline_alert_job__基线告警表 "N" -- "1" tbl_simba_job_base__任务基础数据表
tbl_simba_job_base_publish_alert__周期任务报警表 "N" -- "1" tbl_simba_job_base__任务基础数据表
tbl_simba_job_his_version__任务版本历史表 "N" -- "1" tbl_simba_job_base__任务基础数据表
tbl_simba_dqc_subscribe__订阅告警表 "N" -- "1" tbl_simba_job_base__任务基础数据表
tbl_simba_job_base_publish_alert_record__报警触发表周期 "N" -- "1" tbl_simba_job_base__任务基础数据表
tbl_simba_job_log__任务执行日志表 "N" -- "1" tbl_simba_job_base__任务基础数据表
tbl_simba_job_instance__任务实例表 "N" -- "1" tbl_simba_job_base__任务基础数据表
tbl_simba_alarm_set__报警设置表 "N" -- "1" tbl_simba_job_base__任务基础数据表
tbl_simba_job_output_table__任务输出表 "N" -- "1" tbl_simba_job_base__任务基础数据表
tbl_simba_model__算法模型 "N" -- "1" tbl_simba_job_base__任务基础数据表
tbl_simba_job_input_table__任务输入表 "N" -- "1" tbl_simba_job_base__任务基础数据表
tbl_simba_baseline_job_v2__基线告警表 "N" -- "1" tbl_simba_job_base__任务基础数据表
tbl_simba_job_base_publish__任务基础数据发布表 "N" -- "1" tbl_simba_job_base__任务基础数据表
tbl_simba_online_job_base_alert__实时任务报警表 "N" -- "1" tbl_simba_job_base__任务基础数据表
tbl_simba_alarm_log__报警记录表 "N" -- "1" tbl_simba_job_base__任务基础数据表
tbl_simba_job_base__任务基础数据表 "N" -- "1" tbl_simba_job_base__任务基础数据表
tbl_simba_online_job_table "N" -- "1" tbl_simba_job_base__任务基础数据表
@enduml